<a href="https://colab.research.google.com/github/Favour-Aransiola/ML-Practice/blob/main/numpy_practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Differences Between Numpy and Python List

In [74]:
import numpy as np
import sys
from io import StringIO

In [11]:
array_one = [1,2,3,4,5]
array_two = [6,7,8,9,10]
array_three = []


# To multipy the two array,


In [6]:
for i in range(len(array_one)):
  array_three.append(array_one[i]* array_two[i])

In [7]:
print(array_three)

[6, 14, 24, 36, 50]


Numpy Array

In [13]:
array_four = np.array([1,2,3,4,5])
array_five = np.array([6,7,8,9,10])

In [14]:
array_six = array_four*array_five
print(array_six)

[ 6 14 24 36 50]


In [36]:
arranged = np.arange(20,25,1)

In [37]:
print(arranged)

[20 21 22 23 24]


In [55]:
array_one = np.array([[1,2,3,4],
                      [6,7,8,9]])
array_two = np.array([[1,2],
                      [2,3],
                      [3,4],
                      [4,5]])
print(array_one.dot(array_two))

[[ 30  40]
 [ 80 110]]


In [60]:
merged = np.empty(4)
print(merged)

[1.48e-322 1.98e-322 3.95e-322 5.43e-322]


In [68]:
a= np.array([[1],
             [2],
             [3]])
b= np.array([[8],
             [2],
             [1]])
n=4

mean_square_error = ((1/n)*(np.sum(np.power(a-b,2))))

In [70]:
np.savetxt("mse.csv", b)

In [71]:
print(np.loadtxt("mse.csv",delimiter=","))

[8. 2. 1.]


In [80]:
data = '1,2,3, 1\n 4,5,6, xxy '
print(np.genfromtxt(StringIO(data),delimiter=',', autostrip=True))

[[ 1.  2.  3.  1.]
 [ 4.  5.  6. nan]]
