<a href="https://colab.research.google.com/github/Favour-Aransiola/ML-Practice/blob/main/numpy_revision.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Numpy Practice Problems

1. With your high school reunion fast approaching, you decide to get in shape and lose some weight . You record your weight every day for five weeks starting on a Monday.

Given these daily weights, build an array with your average weight per weekend.


In [ ]:
import numpy as np
dailywts = 185 - np.arange(5*7)/5

new_arr =dailywts.reshape(5,7)
# print(new_arr)
print(np.mean(new_arr[:,5:],axis=1))


[183.9 182.5 181.1 179.7 178.3]


2. After binge watching the discovery channel, you ditch your job as a trial lawyer to become a gold miner  . You decide to prospect five locations underneath a 7x7 grid of land. How much gold do you uncover at each location?

In [ ]:
np.random.seed(5555)
gold = np.random.randint(low=0, high=10, size=(7,7))

print(gold)

[[2 3 0 5 2 0 3]
 [8 8 0 7 1 5 3]
 [0 1 6 2 1 4 5]
 [4 0 8 9 9 8 7]
 [4 2 7 0 7 2 1]
 [9 8 9 2 5 0 8]
 [1 9 8 2 6 4 3]]


In [ ]:
pros_loc = np.array([[1,2],
            [4,5],
            [1,6],
            [2,4],
            [5,2]])


total_gold = 0
for i in range(len(pros_loc)):
  total_gold += gold[pros_loc[i][0]][pros_loc[i][1]]

print(total_gold)


15


4. You decide to invest in a series of billboards along interstate 10 to advertise your stylish new chicken restaurant, Chic-fil-A 🐔.

You buy three billboards evenly spaced starting from mile marker 17 and ending on mile marker 28.
You buy another three billboards starting on mile marker 32 and ending on mile marker 36.
In order, from mile marker 17 to 36, your billboards display these ads: A, B, C, C, B, A.
Determine how far each C ad is from your restaurant which is located at mile marker 30.

# ads / restaurant*:   A     B     C   *   C  B  A
# billboards:        --|-----|-----|---|---|--|--|--
# mile markers:       17          28  30  32    36


In [ ]:
import numpy as np
ads_disp = ["A","B","C","*","C","B","A"]
miles_loc = [17,'x', 28, 30, 32,"x", 36 ]
spaced_nums = np.linspace([17,32],[28,36], num=3, axis=1)
print(spaced_nums)

[[17.  22.5 28. ]
 [32.  34.  36. ]]


In [ ]:
c_pos = spaced_nums[[0,1],[2,0]]

In [ ]:
distance = np.abs(c_pos -30)
print(distance)

NameError: name 'c_pos' is not defined

In [ ]:
new_array = np.random.randint(0,7,size=(3,5))

In [ ]:
mask = new_array>3
print(mask)

[[False  True False False False]
 [ True  True False  True  True]
 [ True False False  True  True]]


In [ ]:
new_array[mask] =15
print(new_array)

[[ 2 15  1  0  1]
 [15 15  3 15 15]
 [15  2  0 15 15]]


5. You’re a relationship scientist, and you’ve developed a questionnaire that determines a person’s love score - a real-valued number between 0 and 100. Your theory is that two people with similar love scores should make a good match 👩‍❤️‍💋‍👨

Given the love scores for 10 different people, create a 2-d array where (i,j) gives the absolute difference of the love scores for person i and person j.



In [ ]:
score = np.round(np.random.uniform(0,100,size=10),2)
print(score)

[35.33 16.16 19.02 44.42 41.95 94.34 15.44 81.83 46.85 34.47]


In [ ]:
result = np.zeros((10,10))

for i in range(len(score)):
  for j in range(len(score)):
    result[i][j] = np.abs(score[i]-score[j])

print(result)

[[ 0.   19.17 16.31  9.09  6.62 59.01 19.89 46.5  11.52  0.86]
 [19.17  0.    2.86 28.26 25.79 78.18  0.72 65.67 30.69 18.31]
 [16.31  2.86  0.   25.4  22.93 75.32  3.58 62.81 27.83 15.45]
 [ 9.09 28.26 25.4   0.    2.47 49.92 28.98 37.41  2.43  9.95]
 [ 6.62 25.79 22.93  2.47  0.   52.39 26.51 39.88  4.9   7.48]
 [59.01 78.18 75.32 49.92 52.39  0.   78.9  12.51 47.49 59.87]
 [19.89  0.72  3.58 28.98 26.51 78.9   0.   66.39 31.41 19.03]
 [46.5  65.67 62.81 37.41 39.88 12.51 66.39  0.   34.98 47.36]
 [11.52 30.69 27.83  2.43  4.9  47.49 31.41 34.98  0.   12.38]
 [ 0.86 18.31 15.45  9.95  7.48 59.87 19.03 47.36 12.38  0.  ]]


Alternative Approach

In [ ]:
b= score.reshape((10,1))

In [ ]:
print(np.abs(score-b))

[[ 0.   19.17 16.31  9.09  6.62 59.01 19.89 46.5  11.52  0.86]
 [19.17  0.    2.86 28.26 25.79 78.18  0.72 65.67 30.69 18.31]
 [16.31  2.86  0.   25.4  22.93 75.32  3.58 62.81 27.83 15.45]
 [ 9.09 28.26 25.4   0.    2.47 49.92 28.98 37.41  2.43  9.95]
 [ 6.62 25.79 22.93  2.47  0.   52.39 26.51 39.88  4.9   7.48]
 [59.01 78.18 75.32 49.92 52.39  0.   78.9  12.51 47.49 59.87]
 [19.89  0.72  3.58 28.98 26.51 78.9   0.   66.39 31.41 19.03]
 [46.5  65.67 62.81 37.41 39.88 12.51 66.39  0.   34.98 47.36]
 [11.52 30.69 27.83  2.43  4.9  47.49 31.41 34.98  0.   12.38]
 [ 0.86 18.31 15.45  9.95  7.48 59.87 19.03 47.36 12.38  0.  ]]


6. You’re a vindictive professor 👨‍🏫 and one of your pet peeves is when students rush through their exams. To teach them a lesson, you decide to give zeros to the first three students who score less than sixty, in the order they turned in their exams.

Given a 1-d array of integers, identify the first three values less than sixty and replace them with zero.



In [ ]:
student_submission = np.round(np.random.uniform(10,100,15))
less_than_60= student_submission<60
print(student_submission)

[98. 48. 99. 33. 86. 12. 92. 84. 45. 27. 79. 42. 32. 34. 43.]


In [ ]:

position =less_than_60.nonzero()
student_submission[position[0][0:3]] =0
print(student_submission)

[98.  0. 99.  0. 86.  0. 92. 84. 45. 27. 79. 42. 32. 34. 43.]


6. Eager to make your mark on the PTA, you decide the best way to hide eggs for the upcoming Easter egg hunt is to use NumPy . You represent the field as a 10x10 array of 0s.

Insert 20 random normal values at random (non repeating) locations in the grid. Then you'll know how much candy to hide at each spot.

In [ ]:
field = np.zeros(shape = (10, 10))
generator = np.random.default_rng(1234)
print(field)


[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [ ]:
numbers = np.round(generator.normal(size=20),2)

In [ ]:
val =generator.choice(field.size,len(numbers), replace=False)
field.ravel()[val] = numbers

In [ ]:
print(field)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [ ]:
array_1 = np.random.randint(10,15,size=(2,5))
array_2 = np.ones((2,5))
print(array_1)
print(np.where(array_1<13,array_1+100,array_1-100))

[[13 11 11 10 14]
 [11 11 10 12 12]]
[[-87 111 111 110 -86]
 [111 111 110 112 112]]


1


You’re given a 10x2 array of floats where each row represents a movie. The first column represents the movie’s rating and the second column represents the director’s rating.
Create a third column that represents the overall rating. The overall rating is equal to the movie rating if it exists, otherwise the director’s rating.



In [ ]:
generator = np.random.default_rng(123)
ratings = np.round(generator.uniform(low=0.0, high=10.0, size=(10, 2)))
ratings[[1,2,7,9], [0,0,0,0]] = np.nan


[[ 7.  1.]
 [nan  2.]
 [nan  8.]
 [ 9.  3.]
 [ 8.  9.]
 [ 5.  2.]
 [ 8.  2.]
 [nan  6.]
 [ 9.  2.]
 [nan  5.]]


In [ ]:
overall_rating = np.split(ratings,2, axis=1)
movie_rating, director_rating = overall_rating[0],overall_rating[1]
condensed = np.where(np.isnan(movie_rating), director_rating, movie_rating)

print(np.hstack([ratings,condensed]))

[[ 7.  1.  7.]
 [nan  2.  2.]
 [nan  8.  8.]
 [ 9.  3.  9.]
 [ 8.  9.  8.]
 [ 5.  2.  5.]
 [ 8.  2.  8.]
 [nan  6.  6.]
 [ 9.  2.  9.]
 [nan  5.  5.]]
